### ISSUE TITLE
Set ANY parameter for forward simulation

### ISSUE THREAD

**Issue by dmccloskey** [VirtualPatientEngine/AIAgents4Pharma#2]
As a user, I would like to be able to set any parameter in the model before simulating it. The parameters of interest include initial species concentrations, initial rates, and kinetic parameters. Currently, I can only set the initial concentration for a single species and specify the duration of the simulation.

**Comment by lilijap** [comment]
Functions that could be used with T2B agent would be:
- setting initial concentration of species: function `set_species` and 'initial_concentration' argument (https://basico.readthedocs.io/en/stable/API/basico.html#basico.model_info.set_species)
-  changing initial kinetic parameters: function `set_reaction_parameters` with  arguments `name`, `reaction_name`, `value` (https://basico.readthedocs.io/en/stable/API/basico.html#basico.model_info.set_reaction_parameters)
- changing "global quantities": function `set_parameters` function with `initial_value` argument (https://basico.readthedocs.io/en/stable/API/basico.html#basico.model_info.set_parameters)
