### ISSUE TITLE
Improved documentation using MKDocs

### ISSUE THREAD

**Issue by dmccloskey** [VirtualPatientEngine/AIAgents4Pharma#28]
#### Description:
We propose creating a GitHub-hosted documentation website for the project using MkDocs. The development will be completed in two stages:

#### **Part 1: Tabbed Documentation**
1. **Overview**: The website will feature three primary tabs, each dedicated to one agent. 
2. **Content**:
   - Each tab will include:
     - An **introduction** to the respective agent.
     - Detailed **documentation of the tools/models** associated with that agent.

#### **Part 2: Jupyter Notebook Integration**
1. **Overview**: The website will include a section with multiple Jupyter notebooks to provide step-by-step guidance.
2. **Content**:
   - Each notebook will demonstrate:
     - How to **import the package**.
     - How to **utilize the tools/models** within users' internal projects. Showcasing [search_models](https://github.com/VirtualPatientEngine/AIAgents4Pharma/blob/main/aiagents4pharma/talk2biomodels/tools/search_models.py) will be a good starting point.

**Comment by gurdeep330** [comment]
@dmccloskey 
Can we close this issue?
The website is up and running 👍

https://virtualpatientengine.github.io/AIAgents4Pharma/

**Comment by dmccloskey** [comment]
@gurdeep330 and https://github.com/Rakesh-Seenu nice make-over of the documentation 🤩. Our future open-source users will find this much better than what was previously there.
