### ISSUE TITLE
Allow for changing states or rates at specific time points in a biomodels simulation

### ISSUE THREAD

**Issue by dmccloskey** [VirtualPatientEngine/AIAgents4Pharma#30]
**Is your feature request related to a problem? Please describe.**
We would like to specify more granular simulation conditions beyond just initial starting concentrations. For example, patients are often administered medications on a periodic schedule (e.g., every day or every few weeks). We would like to be able to model the administration of drugs or more generally perturbations that occur at arbitrary time points in the model.

**Describe the solution you'd like**
- Using the Basico function `basico.add_event()` (https://basico.readthedocs.io/en/latest/API/basico.html#basico.model_info.add_event)
example: `add_event('e0', 'Time > 30', [['X', '10']]),`
 where 'X' is species and '10' is the new species valuafter the expression 'Time>30' is satisfied. 'e0' is event's name.

**Comment by dmccloskey** [comment]
@lilijap Please update with the name of the Basico function when you get a chance 🙂.

**Comment by lilijap** [comment]
> @lilijap Please update with the name of the Basico function when you get a chance 🙂.

@dmccloskey, please see my comment above. One function `add_event()` applied multiple times should mimic drug treatment.
